### PR TITLE
POL-542 Add clowdapp for engine

### PR DESCRIPTION
**Pull request by lahavyuv86**

### CODE REVIEW

**Comment by theute** [comment]
Don't we need all the environment variables as we find in e2e-deploy ?
IIUC the plan is to use Clowder for all environments so we'll ultimately need all those variables, or am I missing something ?

**Comment by lahavyuv86** [comment]
I can add them NP, just wanted to know if all is needed or just some of them

**Comment by theute** [comment]
I think only a few are needed for ephemeral, but all will be needed once we start using them for all environments (this is true for the 4 pods)

**Comment by lahavyuv86** [comment]
@theute The env vars were added, please review again

**Comment by theute** [comment]
Worth a try :)

**Pull request merged**
