### PR TITLE
Add support for logging to Sentry

### PR DESCRIPTION
**Pull request by pilhuhn**
Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>

### CODE REVIEW

**Comment by burmanm** [comment]
Do we want to expose environment variable?

**Comment by pilhuhn** [comment]
@burmanm Sorry, I don't understand the question. The Env variables (also to switch it on) would be set in Kube/OpenShift

**Comment by burmanm** [comment]
sentry environment, ``quarkus.log.sentry.environment``

**Comment by pilhuhn** [comment]
I forgot to add it, but it does not matter for operational purposes, as it can still be set from ENV or even -D . The values in application.properties are "fallback" values

**Comment by theute** [comment]
Related PR: https://github.com/RedHatInsights/e2e-deploy/pull/1598

**Pull request merged**
