### PR TITLE
add dependabot

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by bennetelli** [comment]
Somehow there is dependabot configured already, but I can't see where it comes from. 

I would prefer the file based configuration instead of a "hidden" configuration somehow in the github settings.

**Comment by gwenneg** [comment]
I think it's configured in the repository settings. but I can't confirm since I don't have the permissions to access it.

**Comment by bennetelli** [comment]
Me neither. Maybe @theute or @pilhuhn can take a loot at the repository configuration so we can remove dependatbot from there and have it in the repo only.

**Comment by theute** [comment]
Disabled

**Review by gwenneg — APPROVED** [review]

**Pull request merged**
